export { default as LoginForm } from "./Login/Login.jsx"
export { default as RegisterPatient } from "./FrontDeskOperator/RegisterPatient/RegisterPatient.jsx"
export { default as AdmitPatient } from "./FrontDeskOperator/AdmitPatient/AdmitPatient.jsx"
export { default as DoctorDashboard } from "./Doctor/Doctor.jsx"
export { default as Error404 } from "./404/404.jsx"