# Generated by Django 4.1.7 on 2023-03-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HM_System", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment", name="End", field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="stay", name="End", field=models.DateTimeField(null=True),
        ),
    ]
