# Generated by Django 4.1.7 on 2023-03-02 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HM_System', '0002_alter_user_id_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('EmployeeId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Name', models.TextField()),
                ('Address', models.TextField()),
                ('Phone', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('AadharId', models.IntegerField()),
                ('Gender', models.PositiveSmallIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')])),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Start', models.DateTimeField()),
                ('End', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DataOperator',
            fields=[
                ('EmployeeId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Name', models.TextField()),
                ('Address', models.TextField()),
                ('Phone', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('AadharId', models.IntegerField()),
                ('Gender', models.PositiveSmallIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')])),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('EmployeeId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Name', models.TextField()),
                ('Address', models.TextField()),
                ('Phone', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('AadharId', models.IntegerField()),
                ('Gender', models.PositiveSmallIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')])),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FdOperator',
            fields=[
                ('EmployeeId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Name', models.TextField()),
                ('Address', models.TextField()),
                ('Phone', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('AadharId', models.IntegerField()),
                ('Gender', models.PositiveSmallIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')])),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('Code', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('Brand', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('AadharId', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('Address', models.TextField()),
                ('Phone', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.PositiveSmallIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')])),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Number', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.TextField()),
                ('Floor', models.IntegerField()),
                ('Block', models.IntegerField()),
                ('Unavailable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('StayID', models.AutoField(primary_key=True, serialize=False)),
                ('Start', models.DateTimeField()),
                ('End', models.DateTimeField()),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HM_System.patient')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HM_System.room')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('Code', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('Description', models.TextField()),
                ('Cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('TreatmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('Cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Undergoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HM_System.appointment')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HM_System.doctor')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HM_System.patient')),
                ('Stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HM_System.stay')),
                ('Treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HM_System.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('ReportID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('TestResult', models.TextField()),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HM_System.doctor')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HM_System.patient')),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HM_System.test')),
            ],
        ),
        migrations.CreateModel(
            name='Prescribes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dose', models.TextField()),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HM_System.appointment')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HM_System.doctor')),
                ('Medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HM_System.medication')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HM_System.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HM_System.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HM_System.patient'),
        ),
        migrations.AddConstraint(
            model_name='undergoes',
            constraint=models.UniqueConstraint(fields=('Patient', 'Treatment', 'Stay', 'Date'), name='second_constraint'),
        ),
        migrations.AddConstraint(
            model_name='prescribes',
            constraint=models.UniqueConstraint(fields=('Appointment', 'Medication'), name='first_constraint'),
        ),
    ]
