# Generated by Django 4.1.7 on 2023-03-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HM_System", "0007_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
