# Generated by Django 4.1.7 on 2023-03-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HM_System', '0007_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='AadharId',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='Email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dataoperator',
            name='AadharId',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dataoperator',
            name='Email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='AadharId',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fdoperator',
            name='AadharId',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='fdoperator',
            name='Email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='AadharId',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
