# Generated by Django 4.1.7 on 2023-03-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HM_System', '0009_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(null=True),
        ),
    ]
